name: Test Apps


on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Test app
      run: make test

    - name: Update Comment in PR
      uses: thollander/actions-comment-pull-request@v2
      with:
         filePath: testresults
      

